### ISSUE TITLE
Chaining commands

### ISSUE THREAD

**Issue by Albadylic** [akomiqaia/jsCalc#2]
When writing a sum we are only able to operate on two numbers. 

For example, we can calculate ```5*66``` but we can't calculate ```5*6*6```. 

Can you think of a way to alter your code to allow us to chain operations? ⛓

**Comment by akomiqaia** [comment]
Just updated the code. I think issue can be closed now. I just wrapped the whole logic of how the operators replace each other in an `if` statement that allows users to change operator if the current number display is empty but if there is a number it runs a `updateDisplay()` function.
